language: ruby
rvm:
  - "2.1.5"
script: bundle exec rspec spec
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database portfolio_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
