language: ruby
cache: bundler
rvm:
  - "2.1.5"

before_script: "bundle install"
script: "bundle exec cucumber"

branches:
  only:
    - master

addons:
  postgresql: "9.3"

before_script:
  - psql -c "create database portfolio_test;" -U postgres
  - cp config/database.yml.travis config/database.yml

after_success:
  - coveralls
